export const permissoes = {
  SUPER_ADMIN: [
    "/dashboard",
    "/empresas",
    "/usuarios",
    "/modulos",
    "/auditoria",
    "/configuracoes",
  ],

  ADMIN_EMPRESA: [
    "/dashboard",
    "/clientes",
    "/produtos",
    "/categorias",
    "/marcas-produtos",
    "/estoque",
    "/depositos",
    "/movimentacoes",
    "/agenda",
    "/ordens-servico",
    "/usuarios",
    "/unidades-medida",
    "/fornecedores",  
    "/pedidos-compra",
    "/contas-pagar",
    "/contas-receber",
    "/financeiro",
    "/caixas",
    "/caixas/movimentacoes",
    "/vendas"
],

  USUARIO_EMPRESA: [
    "/dashboard",
    "/clientes",
    "/produtos",
    "/estoque",
    "/depositos",
    "/agenda",
    "/ordens-servico",
    "/marcas-produtos",
    "/unidades-medida",
    "/fornecedores",
    "/pedidos-compra",
    "/contas-pagar",  
    "/contas-receber",
    "/financeiro",
    "/caixas",
    "/caixas/movimentacoes",
    "/vendas"
],
};
